# Generated by Django 5.2.4 on 2025-07-15 18:07

import django.core.validators
import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Campeonato',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome', models.CharField(max_length=200)),
                ('ano', models.IntegerField(validators=[django.core.validators.MinValueValidator(2020), django.core.validators.MaxValueValidator(2030)])),
                ('tipo', models.CharField(choices=[('pontos_corridos', 'Pontos Corridos'), ('grupos_mata_mata', 'Grupos + Mata-mata')], default='pontos_corridos', max_length=20)),
                ('numero_grupos', models.IntegerField(default=1, validators=[django.core.validators.MinValueValidator(1), django.core.validators.MaxValueValidator(8)])),
                ('times_por_grupo', models.IntegerField(default=8, validators=[django.core.validators.MinValueValidator(2), django.core.validators.MaxValueValidator(20)])),
                ('classificados_por_grupo', models.IntegerField(default=4, validators=[django.core.validators.MinValueValidator(1), django.core.validators.MaxValueValidator(10)])),
                ('status', models.CharField(choices=[('planejado', 'Planejado'), ('em_andamento', 'Em Andamento'), ('finalizado', 'Finalizado')], default='planejado', max_length=20)),
                ('criado_em', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'verbose_name': 'Campeonato',
                'verbose_name_plural': 'Campeonatos',
                'ordering': ['-ano', 'nome'],
            },
        ),
        migrations.CreateModel(
            name='Equipe',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome', models.CharField(max_length=100)),
                ('escudo', models.ImageField(blank=True, null=True, upload_to='escudos/')),
                ('cidade', models.CharField(max_length=100)),
                ('representante', models.CharField(max_length=100)),
                ('criado_em', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'verbose_name': 'Equipe',
                'verbose_name_plural': 'Equipes',
                'ordering': ['nome'],
            },
        ),
        migrations.CreateModel(
            name='Rodada',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('numero', models.IntegerField()),
                ('nome', models.CharField(blank=True, max_length=100)),
                ('data_prevista', models.DateField(blank=True, null=True)),
                ('campeonato', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='campeonatos.campeonato')),
            ],
            options={
                'verbose_name': 'Rodada',
                'verbose_name_plural': 'Rodadas',
                'ordering': ['campeonato', 'numero'],
                'unique_together': {('campeonato', 'numero')},
            },
        ),
        migrations.CreateModel(
            name='Partida',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('local', models.CharField(blank=True, max_length=200)),
                ('data_hora', models.DateTimeField(blank=True, null=True)),
                ('gols_mandante', models.IntegerField(default=0, validators=[django.core.validators.MinValueValidator(0)])),
                ('gols_visitante', models.IntegerField(default=0, validators=[django.core.validators.MinValueValidator(0)])),
                ('status', models.CharField(choices=[('pendente', 'Pendente'), ('finalizada', 'Finalizada')], default='pendente', max_length=20)),
                ('equipe_mandante', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='partidas_mandante', to='campeonatos.equipe')),
                ('equipe_visitante', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='partidas_visitante', to='campeonatos.equipe')),
                ('rodada', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='campeonatos.rodada')),
            ],
            options={
                'verbose_name': 'Partida',
                'verbose_name_plural': 'Partidas',
                'ordering': ['rodada__numero', 'data_hora'],
            },
        ),
        migrations.CreateModel(
            name='Classificacao',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('grupo', models.CharField(blank=True, max_length=1, null=True)),
                ('jogos', models.IntegerField(default=0)),
                ('vitorias', models.IntegerField(default=0)),
                ('empates', models.IntegerField(default=0)),
                ('derrotas', models.IntegerField(default=0)),
                ('gols_pro', models.IntegerField(default=0)),
                ('gols_contra', models.IntegerField(default=0)),
                ('saldo_gols', models.IntegerField(default=0)),
                ('pontos', models.IntegerField(default=0)),
                ('campeonato', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='campeonatos.campeonato')),
                ('equipe', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='campeonatos.equipe')),
            ],
            options={
                'verbose_name': 'Classificação',
                'verbose_name_plural': 'Classificações',
                'ordering': ['-pontos', '-saldo_gols', '-gols_pro', 'equipe__nome'],
                'unique_together': {('campeonato', 'equipe')},
            },
        ),
        migrations.CreateModel(
            name='Participacao',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('grupo', models.CharField(blank=True, choices=[('A', 'Grupo A'), ('B', 'Grupo B'), ('C', 'Grupo C'), ('D', 'Grupo D'), ('E', 'Grupo E'), ('F', 'Grupo F'), ('G', 'Grupo G'), ('H', 'Grupo H')], max_length=1, null=True)),
                ('campeonato', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='campeonatos.campeonato')),
                ('equipe', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='campeonatos.equipe')),
            ],
            options={
                'verbose_name': 'Participação',
                'verbose_name_plural': 'Participações',
                'unique_together': {('campeonato', 'equipe')},
            },
        ),
    ]
