# Generated by Django 5.2.4 on 2025-07-16 00:01

import django.core.validators
import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('campeonatos', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='partida',
            options={'ordering': ['rodada__numero', 'data_partida', 'horario'], 'verbose_name': 'Partida', 'verbose_name_plural': 'Partidas'},
        ),
        migrations.RenameField(
            model_name='rodada',
            old_name='data_prevista',
            new_name='data_rodada',
        ),
        migrations.RemoveField(
            model_name='partida',
            name='data_hora',
        ),
        migrations.AddField(
            model_name='partida',
            name='data_partida',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='partida',
            name='horario',
            field=models.TimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='partida',
            name='observacoes',
            field=models.TextField(blank=True, help_text='Observações sobre a partida'),
        ),
        migrations.AddField(
            model_name='rodada',
            name='local_padrao',
            field=models.CharField(blank=True, help_text='Local padrão para todas as partidas desta rodada', max_length=200),
        ),
        migrations.AlterField(
            model_name='partida',
            name='status',
            field=models.CharField(choices=[('pendente', 'Pendente'), ('finalizada', 'Finalizada'), ('adiada', 'Adiada'), ('cancelada', 'Cancelada')], default='pendente', max_length=20),
        ),
        migrations.CreateModel(
            name='ConfiguracaoRodada',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('tipo_configuracao', models.CharField(choices=[('manual', 'Manual - Organizador escolhe as partidas'), ('automatica', 'Automática - Sistema distribui aleatoriamente')], default='manual', max_length=20)),
                ('partidas_por_rodada', models.IntegerField(default=1, validators=[django.core.validators.MinValueValidator(1)])),
                ('dias_entre_rodadas', models.IntegerField(default=7, validators=[django.core.validators.MinValueValidator(1)])),
                ('data_inicio_campeonato', models.DateField(blank=True, null=True)),
                ('campeonato', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='configuracao_rodada', to='campeonatos.campeonato')),
            ],
            options={
                'verbose_name': 'Configuração de Rodada',
                'verbose_name_plural': 'Configurações de Rodada',
            },
        ),
    ]
