# Generated by Django 5.2.4 on 2025-07-16 19:39

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('campeonatos', '0002_alter_partida_options_and_more'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='partida',
            options={'ordering': ['rodada__numero', 'data_hora'], 'verbose_name': 'Partida', 'verbose_name_plural': 'Partidas'},
        ),
        migrations.RemoveField(
            model_name='partida',
            name='data_partida',
        ),
        migrations.RemoveField(
            model_name='partida',
            name='horario',
        ),
        migrations.RemoveField(
            model_name='rodada',
            name='data_rodada',
        ),
        migrations.AddField(
            model_name='campeonato',
            name='atualizado_em',
            field=models.DateTimeField(auto_now=True, null=True),
        ),
        migrations.AddField(
            model_name='campeonato',
            name='classificacao_inicial',
            field=models.CharField(choices=[('alfabetica', 'Ordem Alfabética'), ('aleatoria', 'Ordem Aleatória'), ('manual', 'Definição Manual'), ('ranking', 'Por Ranking/Histórico')], default='alfabetica', max_length=20),
        ),
        migrations.AddField(
            model_name='campeonato',
            name='data_fim_prevista',
            field=models.DateField(blank=True, help_text='Data prevista de término', null=True),
        ),
        migrations.AddField(
            model_name='campeonato',
            name='data_inicio',
            field=models.DateField(blank=True, help_text='Data prevista de início', null=True),
        ),
        migrations.AddField(
            model_name='campeonato',
            name='descricao',
            field=models.TextField(blank=True, help_text='Descrição do campeonato'),
        ),
        migrations.AddField(
            model_name='campeonato',
            name='dias_entre_rodadas',
            field=models.IntegerField(default=7, help_text='Intervalo em dias entre rodadas', validators=[django.core.validators.MinValueValidator(1)]),
        ),
        migrations.AddField(
            model_name='campeonato',
            name='fase_inicial_mata_mata',
            field=models.CharField(choices=[('oitavas', 'Oitavas de Final'), ('quartas', 'Quartas de Final'), ('semifinal', 'Semifinal'), ('final', 'Final')], default='quartas', help_text='A partir de qual fase começará o mata-mata', max_length=20),
        ),
        migrations.AddField(
            model_name='campeonato',
            name='local_padrao',
            field=models.CharField(blank=True, help_text='Local padrão para as partidas', max_length=200),
        ),
        migrations.AddField(
            model_name='campeonato',
            name='max_equipes',
            field=models.IntegerField(blank=True, help_text='Número máximo de equipes (deixe em branco para ilimitado)', null=True, validators=[django.core.validators.MinValueValidator(2)]),
        ),
        migrations.AddField(
            model_name='campeonato',
            name='partidas_por_rodada',
            field=models.IntegerField(default=1, help_text='Quantas partidas por rodada (para geração automática)', validators=[django.core.validators.MinValueValidator(1)]),
        ),
        migrations.AddField(
            model_name='campeonato',
            name='permite_empate',
            field=models.BooleanField(default=True, help_text='Se permite empates nas partidas'),
        ),
        migrations.AddField(
            model_name='campeonato',
            name='tipo_geracao_rodada',
            field=models.CharField(choices=[('manual', 'Manual - Organizador define'), ('automatica', 'Automática - Sistema distribui'), ('hibrida', 'Híbrida - Mista')], default='manual', max_length=20),
        ),
        migrations.AddField(
            model_name='partida',
            name='arbitro',
            field=models.CharField(blank=True, help_text='Nome do árbitro', max_length=100),
        ),
        migrations.AddField(
            model_name='partida',
            name='atualizado_em',
            field=models.DateTimeField(auto_now=True, null=True),
        ),
        migrations.AddField(
            model_name='partida',
            name='criado_em',
            field=models.DateTimeField(auto_now_add=True, null=True),
        ),
        migrations.AddField(
            model_name='partida',
            name='data_hora',
            field=models.DateTimeField(blank=True, help_text='Data e horário da partida', null=True),
        ),
        migrations.AddField(
            model_name='partida',
            name='duracao_prevista',
            field=models.IntegerField(default=90, help_text='Duração em minutos', validators=[django.core.validators.MinValueValidator(30)]),
        ),
        migrations.AddField(
            model_name='partida',
            name='penaltis_mandante',
            field=models.IntegerField(blank=True, default=0, null=True, validators=[django.core.validators.MinValueValidator(0)]),
        ),
        migrations.AddField(
            model_name='partida',
            name='penaltis_visitante',
            field=models.IntegerField(blank=True, default=0, null=True, validators=[django.core.validators.MinValueValidator(0)]),
        ),
        migrations.AddField(
            model_name='partida',
            name='resultado_registrado_em',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='rodada',
            name='atualizado_em',
            field=models.DateTimeField(auto_now=True, null=True),
        ),
        migrations.AddField(
            model_name='rodada',
            name='criado_em',
            field=models.DateTimeField(auto_now_add=True, null=True),
        ),
        migrations.AddField(
            model_name='rodada',
            name='data_fim',
            field=models.DateField(blank=True, help_text='Data de fim da rodada', null=True),
        ),
        migrations.AddField(
            model_name='rodada',
            name='data_inicio',
            field=models.DateField(blank=True, help_text='Data de início da rodada', null=True),
        ),
        migrations.AddField(
            model_name='rodada',
            name='grupo',
            field=models.CharField(blank=True, help_text='Grupo específico desta rodada (se aplicável)', max_length=1, null=True),
        ),
        migrations.AddField(
            model_name='rodada',
            name='observacoes',
            field=models.TextField(blank=True, help_text='Observações sobre a rodada'),
        ),
        migrations.AddField(
            model_name='rodada',
            name='partidas_simultaneas',
            field=models.BooleanField(default=True, help_text='Se todas as partidas devem ocorrer no mesmo dia'),
        ),
        migrations.AddField(
            model_name='rodada',
            name='tipo_rodada',
            field=models.CharField(choices=[('fase_grupos', 'Fase de Grupos'), ('oitavas', 'Oitavas de Final'), ('quartas', 'Quartas de Final'), ('semifinal', 'Semifinal'), ('final', 'Final'), ('terceiro_lugar', 'Disputa de 3º Lugar'), ('pontos_corridos', 'Pontos Corridos')], default='pontos_corridos', max_length=20),
        ),
        migrations.AlterField(
            model_name='campeonato',
            name='criado_em',
            field=models.DateTimeField(auto_now_add=True, null=True),
        ),
        migrations.AlterField(
            model_name='campeonato',
            name='status',
            field=models.CharField(choices=[('planejado', 'Planejado'), ('inscricoes_abertas', 'Inscrições Abertas'), ('em_andamento', 'Em Andamento'), ('finalizado', 'Finalizado'), ('cancelado', 'Cancelado')], default='planejado', max_length=20),
        ),
        migrations.AlterField(
            model_name='equipe',
            name='criado_em',
            field=models.DateTimeField(auto_now_add=True, null=True),
        ),
        migrations.AlterField(
            model_name='partida',
            name='status',
            field=models.CharField(choices=[('agendada', 'Agendada'), ('pendente', 'Pendente'), ('em_andamento', 'Em Andamento'), ('finalizada', 'Finalizada'), ('adiada', 'Adiada'), ('cancelada', 'Cancelada'), ('w_o', 'W.O. (Walkover)')], default='agendada', max_length=20),
        ),
        migrations.DeleteModel(
            name='ConfiguracaoRodada',
        ),
    ]
